version: "3.8"

services:
  postgres:
    image: postgres:15.2
    container_name: postgres_pan_shoot
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devdb
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - 15432:5432